### ISSUE TITLE
No CDF Epoch

### ISSUE THREAD

**Issue by mattkjames7** [rstoneback/pysatCDF#1]
Hi, I have been experimenting with pysatCDF, which can successfully read the data that I am trying to look at. The only problem I have is that there is no "epoch" entry in the cdf.data dict. There is definitely an epoch in the file as it is listed in the metadata, not to mention that I can get the epoch values using IDL (yuck!). Is there something that I am missing?
Cheers,
Matt.

**Comment by rstoneback** [comment]
Hi Matt,

  Thanks for checking out pysatCDF. My guess is the epoch variable is of type EPOCH16, which isn’t supported yet. I’ll get it fixed up. 
Is the CDF file you are loading available publicly so I can check it out? 

Cheers,
Russell

**Comment by mattkjames7** [comment]
Hi Russell, 
Thanks for the quick reply! The CDF files I am using are publicly available [here](http://rbsp.space.umn.edu/data/rbsp/rbspa/l3/2012/).
Cheers,
Matt.

**Comment by rstoneback** [comment]
Hi Matt,

  I’ve pushed some code to the repo that should fix things up. 

When re-running 'python setup.py install' if it doesn’t re-compile the Fortran clear out the build directory.

Cheers,
Russell

import pysatCDF
dd = pysatCDF.CDF('rbspa_efw-l3_20120919_v01.cdf')

dd.data['epoch']
Out[5]: 
array(['2012-09-18T19:00:20.472515072-0500',
       '2012-09-18T19:00:26.771920896-0500',
       '2012-09-18T19:00:33.071325952-0500', ...,
       '2012-09-19T18:58:34.048406016-0500',
       '2012-09-19T18:58:41.560549888-0500',
       '2012-09-19T18:58:49.072690944-0500'], dtype='datetime64[ns]')

**Comment by mattkjames7** [comment]
Brilliant, thank you so much for that! It's a great help!
